"use strict";var _={id:function(query){if(!_.isString(query)){console.error('No valid query given.');return null}
return document.getElementById(query)},class:function(query,context){if(!_.isString(query)){console.error('No valid query given.');return null}
if(_.isDefined(context)&&context==null){console.error('No valid element provided as context (parent of some order). This parameter may is optional and remain empty.');return null}
return(context||document).getElementsByClassName(query)},tag:function(query,context){if(!_.isString(query)){console.error('No valid query given.');return null}
if(_.isDefined(context)&&context==null){console.error('No valid element provided as context (parent of some order). This parameter may is optional and remain empty.');return null}
return(context||document).getElementsByTagName(query)},select:function(query,context,callback){if(!_.exists(child)){console.error('No valid element given.');return null}
if(_.isDefined(context)&&context==null){console.error('No valid element provided as context (parent of some order). This parameter may is optional and remain empty.');return null}
if(!('getElementById' in context)){context=document}
if(/^(#?[\w\-]+|\.[\w\-\.]+)$/.test(query)){switch(query.charAt(0)){case '#':return[context.getElementById(query.substr(1))];case '.':return context.getElementsByClassName(query.substr(1).replace(/\./g,' '));default:return context.getElementsByTagName(query)}}
if(context.querySelectorAll){return context.querySelectorAll(n)}
else if(_.isFunction(callback)){callback()}},contains:function(parent,child){if(!_.exists(parent)){console.error('No valid parent element given.');return null}
if(!_.exists(child)){console.error('No valid child element given.');return null}
return(parent==child?!1:parent.contains(child))},exists:function(elem,lookInDOM){if(lookInDOM!==!0){lookInDOM=!1}
if(_.isUndefined(elem)||elem===null){return!1}
return lookInDOM===!0?document.body.contains(elem):!0},create:function(str,settings){if(!_.isString(str)){return console.error('No string given.')}
if(_.isDefined(settings)&&!_.isObject(settings)){return console.error('No valid settings object was provided.')}
let id=str.match(/#[^\.#\s]+/g);let classes=str.match(/\.[^#\s\.]+/g);let elem=document.createElement(str.replace(/#[^\.#\s]+|\.[^#\s]+|\s/g,''));if(id){elem.id=id[0].replace(/#/,'')}
if(classes){elem.className=classes.join(' ').replace(/\./g,'')}
if(_.isDefined(settings)){if(!_.isObject(settings)){console.error('Given settings object is not valid.')}
else{for(let key in settings){if(settings.hasOwnProperty(key)){switch(key){case 'innerHTML':elem.innerHTML=settings[key];break;case 'style':for(let prop in settings[key]){elem.style.setProperty(prop,settings[key][prop])}
break;default:elem.setAttribute(key,settings[key])}}}}}
return elem},append:function(elem1,elem2){if(!_.exists(elem1)){return console.error('First given element does not exist.')}
if(_.isUndefined(elem2)){return console.error('Second given parameter is neither an element, text or a number.')}
if(_.isString(elem2)||_.isNumber(elem2)){elem2=document.createTextNode(elem2)}
elem1.appendChild(elem2)},prepend:function(elem1,elem2){if(!_.exists(elem1)){return console.error('First given element does not exist.')}
if(_.isUndefined(elem2)){return console.error('Second given parameter is neither an element, text or a number.')}
if(_.isString(elem2)||_.isNumber(elem2)){elem2=document.createTextNode(elem2)}
elem1.insertBefore(elem2,elem1.childNodes[0])},after:function(elem1,elem2){if(!_.exists(elem1)){return console.error('First given element does not exist.')}
if(_.isUndefined(elem2)){return console.error('Second given parameter is neither an element, text or a number.')}
if(_.isString(elem2)||_.isNumber(elem2)){elem2=document.createTextNode(elem2)}
elem1.parentNode.insertBefore(elem2,elem1.nextSibling)},before:function(elem1,elem2){if(!_.exists(elem1)){return console.error('First given element does not exist.')}
if(_.isUndefined(elem2)){return console.error('Second given parameter is neither an element, text or a number.')}
if(_.isString(elem2)||_.isNumber(elem2)){elem2=document.createTextNode(elem2)}
elem1.insertBefore(elem2,elem1)},remove:function(elem){if(!_.exists(elem)){elem.parentNode.removeChild(elem)}},empty:function(elem){if(!_.exists(elem)){return console.error('Element does not exist.')}
elem.innerHTML=''},addEvent:function(elem,event,fn,useCapture){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(event)){return console.error('No event name was given.')}
if(!_.isFunction(fn)){return console.error('No function was given.')}
if(useCapture!==!0){useCapture=!1}
if('addEventListener' in elem){elem.addEventListener(event,fn,useCapture)}
else{elem.attachEvent('on'+event,fn)}},removeEvent:function(elem,event,fn,useCapture){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(event)){return console.error('No event name was given.')}
if(!_.isFunction(fn)){return console.error('No function was given.')}
if(useCapture!==!0){useCapture=!1}
if('removeEventListener' in elem){elem.removeEventListener(event,fn,useCapture)}
else{elem.detachEvent('on'+event,fn)}},addClick:function(elem,fn,useCapture){_.addEvent(elem,'click',fn,useCapture)},removeClick:function(elem,fn,useCapture){_.removeEvent(elem,'click',fn,useCapture)},target:function(elem){if(!_.exists(elem)){return console.error('Element does not exist.')}
return elem.target||elem.srcElement},preventDefault:function(elem){elem.preventDefault();elem.stopPropagation()},addClass:function(elem,class_){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(class_)){return console.error('No class name was given.')}
if('classList' in elem){elem.classList.add(class_)}
else if(elem.className.split(" ").indexOf(class_)==-1){elem.className+=' '+class_}},removeClass:function(elem,class_){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(class_)){return console.error('No class name was given.')}
if('classList' in elem){elem.classList.remove(class_)}
else{elem.className=elem.className.replace(new RegExp('\b'+_.escapeRegex(class_)+'\b','g'),' ')}},toggleClass:function(elem,class_){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(class_)){return console.error('No class name was given.')}
if(_.hasClass(elem,class_)){_.removeClass(elem,class_)}
else{_.addClass(elem,class_)}},hasClass:function(elem,class_){if(!_.exists(elem)){return console.error('Element does not exist.')}
if(!_.isString(class_)){return console.error('No class name was given.')}
if('classList' in elem){return elem.classList.contains(class_)}
else if(elem.className.split(" ").indexOf(class_)==-1){return!1}
return!0},getStyle:function(elem,style){if(!_.exists(elem)){return console.error('Element is not defined.')}
if(!_.isString(style)){return console.error('Given style is not a string.')}
if('getComputedStyle' in window){return window.getComputedStyle(elem,null).getPropertyValue(style)}
else if('currentStyle' in elem){return elem.currentStyle[style]}},setStyles:function(elem,styles){if(!_.exists(elem)){return console.error('Element is not defined.')}
if(_.isDefined(styles)&&!_.isObject(styles)){return console.error('No valid styles object was provided.')}
for(let style_name in styles){elem.style.setProperty(style_name,styles[style_name])}},getHeight:function(elem){if(!_.exists(elem)){return console.error('Element is not defined.')}
let r=elem.getBoundingClientRect();return r.bottom-r.top},getWidth:function(elem){if(!_.exists(elem)){return console.error('Element is not defined.')}
let r=elem.getBoundingClientRect();return r.right-r.left},isFunction:function(n){return typeof(n)=='function'},isObject:function(n){return typeof(n)=='object'&&n!==null},isArray:function(n){return _.isDefined(n)&&n!==null&&n.constructor===Array},isString:function(n){return typeof(n)=='string'},isNumber:function(n){return typeof(n)=='number'},isInteger:function(n){return typeof(n)=='number'&&n%1===0},isFloat:function(n){return typeof(n)=='number'&&n%1!==0},isDefined:function(n){return typeof(n)!='undefined'},isUndefined:function(n){return typeof(n)=='undefined'},escapeRegex:function(str){if(!_.isString(class_)){return console.error('No string was given.')}
return(''+str).replace(/[\.\*\+\?\^\$\{\}\(\)\|\[\]\\\/\-]/g,'\\$&')},encodeHTML:function(str){if(!_.isString(str)){return console.error('No string was given.')}
return(''+str).replace(/&/g,'\&amp\;').replace(/</g,'\&lt\;').replace(/>/g,'\&gt\;').replace(/"/g,'\&quot\;').replace(/'/g,'\&#039\;')},decodeHTML:function(str){if(!_.isString(class_)){return console.error('No string was given.')}
return(''+str).replace(/\&amp\;/g,'&').replace(/\&lt\;/g,'<').replace(/\&gt\;/g,'>').replace(/\&quot\;/g,'"').replace(/\&#039\;/g,'\'')},parseJSON:function(str){if(!_.isString(str)){return console.error('No string was given.')}
let obj=null;try{obj=JSON.parse(str)}
catch(err){console.error('Could not parse the given string as JSON, because of a '+err)}
return obj}};var NODE={data_load_btn:null,darkmode_btn:null,play_btn:null,pause_btn:null,stop_btn:null,time_btn:{slow:null,normal:null,fast:null,},initializeNavButtons:function(){this.data_load_btn=_.id('load-data');this.darkmode_btn=_.id('toggle-darkmode');this.play_btn=_.id('play-button');this.pause_btn=_.id('pause-button');this.stop_btn=_.id('stop-button');this.time_btn.slow=_.id('animation-speed-0-5');this.time_btn.normal=_.id('animation-speed-1-0');this.time_btn.fast=_.id('animation-speed-2-0')},data_load_window:null,close_btn:null,blur:null,drop_area:null,select_file_input:null,window_example_sets_area:null,file_reader_notice:null,initializeDataLoadWindow:function(){this.data_load_window=_.id('data-load-window');this.close_btn=_.class('close',this.data_load_window)[0];this.blur=_.class('blur',this.data_load_window)[0];this.window_example_sets_area=_.id('example-set-area');this.file_reader_notice=_.id('file-reader-notice');this.select_file_input=_.id('selected-file');this.drop_area=_.id('drop-area')},current_value:{container:null,value:null,indicator:null},data_set_info:{title:null,date:null},column_chart:null,initializeColumnChart:function(){let context=_.id('data-set-info');this.data_set_info.title=_.class('title',context)[0];this.data_set_info.date=_.class('date',context)[0];this.column_chart=_.id('column-chart');let curr=this.current_value;curr.container=_.id('data-set-current-value');curr.value=_.class('value',curr.container)[0];curr.indicator=_.class('indicator',curr.container)[0]},individual_chart_menu:null,individual_chart:null,back_to_column_chart_btn:null,download_png_btn:null,compare_btn:null,initializeIndividualCharts:function(){this.individual_chart_menu=_.id('individual-chart-menu');this.back_to_column_chart_btn=_.id('back-to-column-chart-btn');this.download_png_btn=_.id('download-chart-as-image');this.compare_btn=_.id('compare-btn');this.individual_chart=_.id('individual-chart')},initialize:function(){this.html=_.tag('html')[0];this.head=_.tag('head')[0];this.body=_.tag('body')[0];this.initializeNavButtons();this.initializeDataLoadWindow();this.initializeColumnChart();this.initializeIndividualCharts()}}
var NAV={darkmode:!1,individual_chart_opened:!1,initialize:function(){_.addClick(NODE.data_load_btn,DATA_LOAD.open);_.addClick(NODE.darkmode_btn,this.toggleDarkMode);_.addClick(NODE.play_btn,ANIMATOR.play);_.addClick(NODE.pause_btn,ANIMATOR.pause);_.addClick(NODE.stop_btn,ANIMATOR.stop);_.addClick(NODE.time_btn.slow,NAV.setHalvedTime);_.addClick(NODE.time_btn.normal,NAV.setNormalTime);_.addClick(NODE.time_btn.fast,NAV.setDoubledTime)},setActive:function(btn){_.addClass(btn,'active')},setInactive:function(btn){_.removeClass(btn,'active')},setExclusiveActive:function(btn){let btns=NODE.time_btn;for(let key in btns){if(btns[key]===btn){this.setActive(btns[key])}
else{this.setInactive(btns[key])}}},toggleChart:function(){if(NAV.individual_chart_opened){NAV.showColumnChart()}
else{NAV.showIndividualChart()}},showColumnChart:function(){NAV.individual_chart_opened=!1;_.addClass(NODE.column_chart,'active');_.removeClass(NODE.current_value.container,'hidden');_.removeClass(NODE.individual_chart,'active');_.removeClass(NODE.individual_chart_menu,'active');ANIMATOR.refreshFrame()},showIndividualChart:function(){NAV.individual_chart_opened=!0;_.removeClass(NODE.column_chart,'active');_.addClass(NODE.current_value.container,'hidden');_.addClass(NODE.individual_chart,'active');_.addClass(NODE.individual_chart_menu,'active');ANIMATOR.refreshFrame()},toggleDarkMode:function(){NAV.darkmode=!NAV.darkmode;_[(NAV.darkmode?'add':'remove')+'Class'](NODE.html,'darkMode');ANIMATOR.refreshFrame()},setHalvedTime:function(){NAV.setExclusiveActive(NODE.time_btn.slow);ANIMATOR.setTime(0.5)},setNormalTime:function(){NAV.setExclusiveActive(NODE.time_btn.normal);ANIMATOR.setTime(1.0)},setDoubledTime:function(){NAV.setExclusiveActive(NODE.time_btn.fast);ANIMATOR.setTime(2.0)},downloadChartImage:function(){let image_uri=NODE.individual_chart.toDataURL('image/png');let date=new Date();let day=date.getDate();let month=date.getMonth()+1;let date_str=(day>9?'':'0')+day+'-'+(month>9?'':'0')+month+'-'+date.getFullYear()+' '+date.getHours()+'-'+date.getMinutes()+'-'+date.getSeconds();let link=_.create('a',{'download':'chart '+ANIMATOR.individual_chart_keys[0].replace(/[^a-z0-9\-\_]/g,'')+' '+date_str+'.png','href':image_uri});_.append(NODE.body,link);link.click();_.remove(link)}}
var DATA_LOAD={initialize:function(){_.addClick(NODE.blur,this.close);_.addClick(NODE.close_btn,this.close);this.initializeDropArea()},open:function(){_.addClass(NODE.data_load_window,'visible');setTimeout(function(){NODE.close_btn.focus()},100)},close:function(){_.removeClass(NODE.data_load_window,'visible');_.removeClass(NODE.data_load_window,'file-selected');NODE.data_load_btn.focus()},initializeDropArea:function(){if(typeof(window.FileReader)!=='function'){_.addClass(NODE.file_reader_notice,'show')}
_.addEvent(NODE.drop_area,'dragenter',_.preventDefault);_.addEvent(NODE.drop_area,'dragover',_.preventDefault);_.addEvent(NODE.drop_area,'dragleave',_.preventDefault);_.addEvent(NODE.drop_area,'drop',_.preventDefault);_.addEvent(NODE.drop_area,'dragenter',this.highlightDropArea);_.addEvent(NODE.drop_area,'dragover',this.highlightDropArea);_.addEvent(NODE.drop_area,'dragleave',this.unhighlightDropArea);_.addEvent(NODE.drop_area,'drop',this.unhighlightDropArea);_.addEvent(NODE.drop_area,'drop',this.handleDroppedFile);_.addEvent(NODE.select_file_input,'change',this.handleSelectedFile)},highlightDropArea:function(){_.addClass(NODE.drop_area,'dragged-over')},unhighlightDropArea:function(){_.removeClass(NODE.drop_area,'dragged-over')},handleDroppedFile:function(e){_.preventDefault(e);let file=null;if(e.dataTransfer.items){let items=e.dataTransfer.items;if(items.length>1){alert('Dropping multiple files is forbidden.');return}
if(items[0].kind==='file'){file=items[0].getAsFile()}
else{alert('Please drop a file.');return}}
else{let items=e.dataTransfer.files;if(items.length>1){alert('Dropping multiple files is forbidden.');return}
let file=items[0]}
DATA_LOAD.processFile(file)},handleSelectedFile:function(e){let items=this.files;let file=items[0];DATA_LOAD.processFile(file)},processFile:function(file){if(typeof(window.FileReader)!=='function'){alert('The FileReader API is not supported by your browser. Please update your browser or switch to a different one!');return}
if(!file){console.error('File is not defined.');return}
if(!/\.(json|txt)$/.test(file.name)){alert('Only .json and .txt files are allowed.');return}
if(file.size>10000){if(!confirm('This data set is large ('+(file.size/1000)+'KB) and may freeze your tab momentarily. Do you want to continue?')){return}}
var reader=new FileReader();reader.readAsText(file,'UTF-8');reader.onerror=function(e){alert('File could not be read.')}
reader.onload=function(e){DATA_LOAD.parseJSON(_.target(e).result)}},parseJSON:function(str){let obj=_.parseJSON(str);if(!obj){alert('Could not parse the file as it is not in a valid JSON format.\nCheck your browser console for more information.');return!1}
DATA_LOAD.visualizeObject(obj,!0)},visualizeObject:function(obj,showConfirmation){let ani={};let columns={};let info=NODE.data_set_info;info.title.innerHTML=obj.name;info.date.innerHTML=obj.date;_.empty(NODE.column_chart);let counter=0;for(let key in obj.data){if(!obj.data.hasOwnProperty(key)){return}
let column=this.getColumn(key,counter,obj.keys[key].name,obj.keys[key].icon);_.append(NODE.column_chart,column);columns[key]={'container':column,'name':obj.keys[key].name,'meter':_.class('meter',column)[0],'value':_.class('value',column)[0],'start_order':counter};_.addClick(column,function(e){let column_key=_.target(e).getAttribute('column-id');ANIMATOR.setInvidualChartKeys([column_key]);NAV.showIndividualChart()});ani[key]=this.generateDataPointArray(obj.data[key],obj.range.from,obj.range.to);counter++}
ANIMATOR.setRange(obj.range.from,obj.range.to);ANIMATOR.setData(ani);ANIMATOR.setColumns(columns);ANIMATOR.end();ANIMATOR.refreshFrame();_.removeClass(NODE.current_value.container,'hidden');NAV.showColumnChart();if(showConfirmation===!0){_.addClass(NODE.data_load_window,'file-selected')}},getColumn:function(key,column_index,key_name,icon_url){let container=_.create('button.column-container');let clickEvent=_.create('div.clickEvent',{'title':'Open statistics for '+key_name,'column-id':key});let icon=_.create('img.icon',{'src':_.isString(icon_url)?_.encodeHTML(icon_url):''});let column=_.create('div.column');let meter=_.create('div.meter',{'style':{'background':this.getColumnColor(column_index)}});let name=_.create('div.name',{'innerHTML':key_name});let value=_.create('div.value');_.append(meter,name);_.append(meter,value);_.append(column,meter);_.append(container,icon);_.append(container,column);_.append(container,clickEvent);return container},getColumnColor:function(index){let colors=['#099b9b','#a52a2a','#9f8605','#556b2f','#8b008b','#1616ad','#bf775f','#888236','#5ebf5e','#9932cc','#3f238d','#800000','#a2651b','#808000','#800080'];return colors[index%colors.length]},generateDataPointArray:function(data,from,to){function checkForValidValue(val){if(!_.isNumber(val)){throw 'Error: Value "'+value+'" for key "'+i+'" in JSON must be a number, but is a "'+typeof(value)+'".'}}
let data_points=[];for(let i=from;i<=to;i++){if(_.exists(data[i+""])&&_.isNumber(data[i+""])){let value=data[i+""];checkForValidValue(value);if(!_.isNumber(value)){throw 'Error: Value "'+value+'" for key "'+i+'" in JSON must be a number, but is a "'+typeof(value)+'".'}
data_points[data_points.length]=value;continue}
if(i==from){data_points[data_points.length]=0;continue}
let prev=data_points[data_points.length-1];let next=null;let steps=0;for(let j=i+1;j<=to;j++){steps++;if(_.exists(data[j+""])){next=data[j+""];checkForValidValue(next);break}}
let average=prev+((next-prev)/(1+steps));data_points[data_points.length]=next==null?prev:average}
let upscaled_data_points=[];let len=data_points.length;for(let i=0;i<len;i++){let curr=data_points[i];let num=upscaled_data_points.length;upscaled_data_points[num]=curr;if(i==len-1){break}
let next=data_points[i+1];let diff=next-curr;let hundreth=diff/100;for(let j=2;j<=98;j+=2){let new_point=curr+(j*hundreth);let len=upscaled_data_points.length;upscaled_data_points[len]=new_point}}
return upscaled_data_points}}
var COMPARE={open:function(){}}
var ANIMATOR={is_running:!1,time:1.0,from:0,to:0,current:0,loop:null,data:{},columns:{},column_num:0,pixels_between_columns:52,individual_chart_keys:[],initialize:function(){_.addEvent(window,'resize',function(){if(NAV.individual_chart_opened){ANIMATOR.refreshFrame()}});_.addClick(NODE.back_to_column_chart_btn,NAV.showColumnChart);_.addClick(NODE.download_png_btn,NAV.downloadChartImage);_.addClick(NODE.compare_btn,COMPARE.open)},setRange:function(from,to){this.from=from;this.to=to;this.current=0},setTime:function(time){this.time=time;if(this.is_running){this.stopLoop();this.startLoop()}
this.setCSSTransitions()},setCSSTransitions:function(){for(let column in this.columns){_.setStyles(this.columns[column].meter,{'transition':((1/this.time)/5)+'s'})}},setData:function(obj){this.data=obj;let first_key=Object.keys(obj)[0];this.data_point_num=obj[first_key].length},setColumns:function(obj){this.columns=obj;this.column_num=Object.keys(obj).length;this.setCSSTransitions()},setInvidualChartKeys:function(keys){this.individual_chart_keys=keys},startLoop:function(){let interval=80/ANIMATOR.time;ANIMATOR.loop=setInterval(ANIMATOR.update,interval)},stopLoop:function(){clearInterval(ANIMATOR.loop);ANIMATOR.loop=null},play:function(){ANIMATOR.is_running=!0;_.removeClass(NODE.html,'animation-paused');_.addClass(NODE.html,'animation-playing');ANIMATOR.startLoop()},pause:function(){ANIMATOR.is_running=!1;_.removeClass(NODE.html,'animation-playing');_.addClass(NODE.html,'animation-paused');ANIMATOR.stopLoop()},restart:function(){ANIMATOR.current=0},end:function(){ANIMATOR.is_running=!1;ANIMATOR.current=0;_.removeClass(NODE.html,'animation-playing');_.addClass(NODE.html,'animation-paused');ANIMATOR.stopLoop()},stop:function(){ANIMATOR.end();ANIMATOR.update()},number_names:{'Thousand':Math.pow(10,3),'Million':Math.pow(10,6),'Billion':Math.pow(10,9),'Trillion':Math.pow(10,12),'Quadrillion':Math.pow(10,15),'Quintillion':Math.pow(10,18),'Sextillion':Math.pow(10,21),'Septillion':Math.pow(10,24),'Octillion':Math.pow(10,27),'Nonillion':Math.pow(10,30),'Decillion':Math.pow(10,33),'Undecillion':Math.pow(10,36),'Duodecillion':Math.pow(10,39),'Tredecillion':Math.pow(10,42),'Quattuordecillion':Math.pow(10,45),'Quindecillion':Math.pow(10,48),'Sexdecillion':Math.pow(10,51),'Septendecillion':Math.pow(10,54),'Octodecillion':Math.pow(10,57),'Novemdecillion':Math.pow(10,60),'Vigintillion':Math.pow(10,63),'*10^66':Math.pow(10,66),'*10^69':Math.pow(10,69),'*10^72':Math.pow(10,72),'*10^75':Math.pow(10,75),'*10^78':Math.pow(10,78),'*10^81':Math.pow(10,81),'*10^84':Math.pow(10,84),'*10^87':Math.pow(10,87),'*10^90':Math.pow(10,90),'*10^93':Math.pow(10,93),'*10^96':Math.pow(10,96),'*10^99':Math.pow(10,99)},formatNumber:function(num){let is_negative=num<0?!0:!1;let sign=is_negative?'-':'';let word='';let short=0;if(is_negative){num*=-1}
if(num<1000){return sign+num}
for(let name in ANIMATOR.number_names){let value=ANIMATOR.number_names[name];if(num>=value&&num<value*1000){return sign+Number(num/value).toFixed(1)+' '+name}}
return sign+'&infin;'},update:function(){if(ANIMATOR.data==null){return}
if(ANIMATOR.current>=ANIMATOR.data_point_num){ANIMATOR.end();return}
ANIMATOR.refreshFrame();ANIMATOR.current++},refreshFrame:function(){if(ANIMATOR.current%50==0){let curr_val=parseInt(ANIMATOR.from)+(ANIMATOR.current==0?0:ANIMATOR.current/50);NODE.current_value.value.innerHTML=curr_val;NODE.current_value.indicator.innerHTML=curr_val}
_.setStyles(NODE.current_value.indicator,{'width':(ANIMATOR.current%50*2)+'%'});if(NAV.individual_chart_opened){ANIMATOR.updateIndividualCharts()}
else{ANIMATOR.updateColumnChart()}},updateColumnChart:function(){let $=ANIMATOR;let min=0;let max=Number.MIN_VALUE;let all_values=[]
for(let key in $.data){let val=$.data[key][$.current];if(val<min)min=val;if(val>max)max=val;all_values[all_values.length]={'key':key,'value':val}}
let diff=max-min;for(let key in $.data){let curr=$.data[key][$.current];$.columns[key].value.innerHTML=$.formatNumber(curr);_.setStyles($.columns[key].meter,{'width':(((curr-min)/(max-min))*100)+"%"})}
function sortObject(obj,property){return obj.sort(function(a,b){return a[property]<b[property]?1:-1})}
let sorted_values=sortObject(all_values,'value');for(let i=0;i<$.column_num;i++){let column=$.columns[sorted_values[i].key];let transform_by=(i-column.start_order)*$.pixels_between_columns;_.setStyles(column.container,{'transform':'translate(0px, '+transform_by+'px)'})}},updateIndividualCharts:function(){let $=ANIMATOR;let canvas=NODE.individual_chart;let context=canvas.getContext('2d');let keys=$.individual_chart_keys;let key_num=$.individual_chart_keys.length;canvas.width=_.getWidth(NODE.individual_chart_menu);canvas.height=500+(18*(key_num-1));context.clearRect(0,0,canvas.width,canvas.height);let min=0;let max=Number.MIN_VALUE;for(let i=0;i<key_num;i++){for(let j=0;j<$.data_point_num;j++){let key=keys[i];let val=$.data[key][j];if(val<min)min=val;if(val>max)max=val}}
let padding={top:5,left:5,bottom:80,right:5};let label_font='12px Arial sans-serif';let label_top=ANIMATOR.formatNumber(max)+'';let label_bottom=ANIMATOR.formatNumber(min)+'';context.font=label_font;let label_top_width=context.measureText(label_top).width;let label_bottom_width=context.measureText(label_bottom).width;let max_width=label_top_width;if(max_width<label_bottom_width)max_width=label_bottom_width;padding.right=padding.right+max_width+15;padding.bottom=padding.bottom+18*key_num;for(let i=0;i<2;i++){context.font=label_font;context.fillStyle=NAV.darkmode?'#767676':'#b5b5b5';context.textBaseline=i==0?'top':'bottom';context.textAlign='left';context.fillText(i==0?label_top:label_bottom,canvas.width-padding.right+5,i==0?padding.top:canvas.height-padding.bottom);context.stroke()}
let width_minus_padding=canvas.width-padding.left-padding.right;let number_of_keys=(($.data_point_num-1)/50)+1;for(let i=$.from;i<=$.to;i++){context.strokeStyle=NAV.darkmode?'#242424':'#ededed';let x_pos=i==$.from?padding.left:padding.left+(width_minus_padding*((i-$.from)/(number_of_keys-1)));context.moveTo(x_pos,padding.top);context.lineTo(x_pos,canvas.height-padding.bottom);context.stroke();let limited_labels=!1;let text=i+'';let text_width=context.measureText(text).width;if(text_width>100){return}
else if(text_width>35){limited_labels=!0}
else if(window.innerWidth<=550){limited_labels=!0}
if(limited_labels&&$.from!=i&&$.to!=i){continue}
context.font=label_font;context.fillStyle=NAV.darkmode?'#767676':'#b5b5b5';context.textBaseline='bottom';context.textAlign=i==$.from?'left':(i==$.to?'right':'center');context.fillText(text,x_pos,canvas.height-padding.bottom+20);context.stroke()}
context.font='14px Arial sans-serif';context.fillStyle=NAV.darkmode?'#767676':'#b5b5b5';context.textBaseline='middle';context.textAlign='left';context.fillText('Legend',padding.left,canvas.height-padding.bottom+50);context.stroke();for(let i=0;i<key_num;i++){let key=keys[i];let color=_.getStyle($.columns[key].meter,'background-color');$.drawIndividualKey(canvas,context,padding,color,min,max,$.data[key],key);let y_pos=canvas.height-padding.bottom+66+(18*i);context.font='12px Arial sans-serif';context.fillStyle=NAV.darkmode?'#767676':'#b5b5b5';context.textBaseline='top';context.textAlign='left';context.fillText($.columns[key].name,padding.left+20,y_pos);context.stroke();context.rect(padding.left+4,y_pos,10,10);context.fillStyle=color;context.fill();context.stroke()}
if($.current!=0&&$.current!=$.data_point_num-1){context.strokeStyle='#e26565';let width_ratio=($.current+1)/$.data_point_num;let x_pos=padding.left+width_minus_padding*width_ratio;context.moveTo(x_pos,padding.top);context.lineTo(x_pos,canvas.height-padding.bottom);context.stroke()}},drawIndividualKey:function(canvas,context,padding,color,min,max,data,key){let point_radius=2;let width_minus_padding=canvas.width-padding.left-padding.right;let height_minus_padding=canvas.height-padding.top-padding.bottom;let points=[];let points_num=points.length;for(let i=0;i<=ANIMATOR.data_point_num;i+=50){let width_ratio=(i+1)/ANIMATOR.data_point_num;let x_pos=i==0?padding.left:padding.left+width_minus_padding*width_ratio;let percentage_to_top=(((data[i]-min)/(max-min))*100);let y_pos=canvas.height-padding.bottom-(height_minus_padding/(100/percentage_to_top));points[points.length]={x:x_pos,y:y_pos};points_num++}
let start_angle=0;let end_angle=2*Math.PI;context.strokeStyle=color;for(let i=0;i<points.length;i++){let x=points[i].x;let y=points[i].y;context.beginPath();context.arc(x,y,point_radius,start_angle,end_angle);context.stroke();if(i!=points.length-1){let x_next=points[i+1].x;let y_next=points[i+1].y;context.moveTo(x,y);context.lineTo(x_next,y_next);context.stroke()}}}}
var MAIN={initialize:function(){NODE.initialize();NAV.initialize();DATA_LOAD.initialize();ANIMATOR.initialize();MAIN.loadExampleDataset()},loadExampleDataset:function(){let request=new XMLHttpRequest();request.open('GET','data/example-data-set.json');request.send();request.onreadystatechange=function(e){if(request.readyState===4&&request.status===200){let json_text=request.responseText;if(json_text!=null&&json_text!=''){let json_obj=_.parseJSON(json_text);DATA_LOAD.visualizeObject(json_obj)}}}
request.onerror=MAIN.showXMLHttpWarnings},showXMLHttpWarnings:function(){let error_msg=_.create('div.notice.red',{'innerHTML':'<b>Loading the example data set failed.</b><br />Are you running this project locally on your system? Try using the <i>Load data</i> button.'});_.append(NODE.column_chart,error_msg);let warning=_.create('div.notice.blue',{'innerHTML':'You may currently run this project locally on your computer. This restricts you from selecting local files as data sets, excluding directly loading online examples.','style':{'margin-bottom':'20px'}});_.empty(NODE.window_example_sets_area);_.append(NODE.window_example_sets_area,warning)}}
_.addEvent(window,'load',MAIN.initialize)